### ISSUE TITLE
License violations (ToaruOS, NCSA/UofI License terms)

### ISSUE THREAD

**Issue by klange** [PoisonNinja/iris#4]
Hello again,

I have noticed that through the fault of a search/replace algorithm, you have made modifications to the license text of sources in this repository derived from ToaruOS, in violation of that license. Please correct the license terms to appropriately identify the copyright owners.

Additionally, your search/replace operation has resulted in an erroneous URL presented in the license file, which you will likely want to fix anyway.

**Comment by PoisonNinja** [comment]
I deleted helix, so that should resolve the license violation issue for that.

a77cd77 should fix the URL and naming issues in LICENSE.md

98b8c97 fixes the license text for source code.

**Comment by klange** [comment]
That looks like it should do it. Thanks!
